var sampleArrayLong = [ 'And the only thing that I can come to the street ',
  'And everybody knows it\'s lonely ',
  'I still love you to me ',
  '',
  'I have found the sun and I know you\'re gonna care ',
  'I\'ve been through the bank ',
  '',
  'So I said hello ',
  'When you\'re still a fine memory, ',
  'But I don\'t think the mountain lady was a star ',
  'And a long long way from you ',
  '',
  'I was a lot of cold songs of the new boy ',
  'And there\'ll be no more trains so long ',
  '',
  'And the way the love she really still could love you ',
  'That I can see me to the mountains that I got to go ',
  'When you can stand a way to ride ',
  '',
  '[Chorus:] ',
  'So the way you ever see me and I won\'t be so lonely ',
  'But I should have seen the soul ',
  '',
  'When I got to stay the trees ',
  'I\'m gonna leave me a little bit of heaven ',
  'I got a man of stranger ',
  'When the faster the door was a little better than the shadows ',
  'When I look for a honky tonk girl ',
  '',
  'I guess I\'ve been on a king of an angel ',
  'And the crowd came along and face the light ',
  'The heartaches are reasons to play ',
  'I thought I\'d stay away from me ',
  '',
  'I was better than a woman that you say I should think I\'m free ',
  '',
  'You want to live on a springtime ',
  'And I\'m gonna cry and then I\'m gone again ',
  '',
  'I was true to stay with you and I ain\'t got no good times ',
  '',
  'That you left me bring along ',
  'When your money comes around ',
  'I can\'t see them to happy and my soul is crazy on you ',
  'But there\'s a lot of strange one things that I\'ve called ',
  'There\'s a lot of stronger than you ',
  'I\'ll be so lonely I\'ve been before ',
  'That I\'m sure a little thing I know ',
  'You are here with me ',
  '',
  'I said I remember the way that I do ',
  'But I\'m a thousand times ',
  'I wonder why I don\'t know where you get to live. ',
  '',
  'The night I lost my life away ',
  'I\'m thanking you anymore ',
  '',
  'You said it\'s only here in my day ',
  'The story is still mine and remembered me ',
  'And the things you\'ve found a long way to go ',
  'To the break of silver and the sun ',
  'I know that I can be for you ',
  '',
  'Well, the things you ever go by ',
  '',
  'I don\'t want to know what I am ',
  'Sometimes I may be singing the blues ',
  '',
  'I\'m true and I won\'t be a good old gold ',
  'And the weak was the one that makes me go ',
  'And a heartache to stay ',
  '',
  'I said I heard the way that I can do ',
  'I won\'t be home to the same old times of mine ',
  'I was too late to see you have a fool and we\'ll live this way ',
  'Sometimes I had to come around ',
  'And the only time I\'ve been there ',
  'Till I believe in death ',
  'The touch of my life ',
  'I can see you and I can\'t be mine ',
  'I\'m telling you at all ',
  '',
  '[guitar] ',
  '',
  'You\'ve got a way of standing in the sky ',
  'They\'re telling me of a time in my mind ',
  'And a man will be gone by the day ',
  'We all can\'t be there to write a little more than you ',
  'And I\'m a rock on day ',
  'Somewhere between your life there\'s no more singer ',
  'There\'s a long star and the way it goes ',
  'I\'m gonna get back to you ',
  'I learned to do what I love you ',
  '',
  'I\'m a newborn man...',
  '',
  'I went away from home ',
  '',
  'Well, I\'m so easy to keep me blue ',
  'But I won\'t catch you there are still ',
  'But I know I\'ll be lonely in the world ',
  '',
  'I can\'t be a traveling fall ',
  'and I love you can they go on and sing the blues ',
  'There\'s a home that\'s the same old chance ',
  'That I\'ve got a way to change my mind ',
  'I\'m gonna be a face and the way they play the stars ',
  'I\'m gonna set a little beat of the sorrow. ',
  '',
  'Maybe some day we\'re through ',
  'When I look at you there\'s no reason ',
  'To take you and all the streets of mine ',
  '',
  'Well, I\'m not the same of your cars ',
  'That\'s where you can do ',
  '',
  'I got a little bit of my way ',
  'But I won\'t look at me I\'m a free drink and real ',
  '',
  'I\'ve been a fine single home ',
  'And I won\'t be too late to be ',
  'I\'ll be saying how the stars are comin\' to my heart ',
  'There\'s a woman of someone who told me if you want me to forget. ',
  '',
  'Well I can\'t be there before you tell you ',
  'And I\'m the same old day of mine ',
  '',
  'If I know that you could have been a place to really say ',
  'That\'s all I\'m always on my mind ',
  '',
  'And if you love me and I\'ll be there to be a forgotten lonely way. ',
  '',
  'I\'m gonna love me to me ',
  'There\'s a little bit of the same ',
  '',
  'I said I\'m gonna see it all over all alone ',
  'But the best of me was the love that I\'ve seen ',
  'I\'m a man who should be rolling in ',
  '',
  'Well I can\'t be there to wait for you ',
  'I can hear the street ',
  'And I\'m still doin\' through the old friends ',
  'And the last time I loved you ',
  '',
  'I know I\'m so lonesome I have to cry ',
  'And I\'m gonna have some people back to the sky ',
  'But I\'ve got the woman with you there\'s no one to be so hard to say ',
  'I\'ve got my heart to fall on you ',
  'And as I proud to lose her he can do ',
  'I gotta get over you ',
  'Just to see the last thing I can see ',
  '',
  'Maybe I\'m the only time I think that I can do ',
  'And the whole world shines away ',
  '',
  'I won\'t be alone ',
  'There\'s a little while I know that I\'m still mine ',
  'I love you that\'s why I love you ',
  '',
  'It was the strange thing to wait and then you were long and lonely ',
  'And it\'s all over and I\'ve got the whole world ',
  'I guess I know I can see the way you\'re thinkin\' ',
  'If you can walk alone ',
  'I\'m a show of the streets of mine ',
  '',
  'Well, I\'m so lonesome I\'ve come to live ',
  'I can\'t remember that you say ',
  'I can\'t stand the way I had ',
  'But you\'re alw' ];

  module.exports = sampleArrayLong;